name: dnnbugs

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: dnnbugs-build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Run Python script
        run: bash reproduce_all.sh